openapi: 3.0.3
info:
  title: Markdown Image Upload API
  version: 6.1.0
  description: API surface used to upload local images and attach them to tickets or comments.
servers:
  - url: https://{redmineHost}
    variables:
      redmineHost:
        default: redmine.example.com
security:
  - ApiKeyAuth: []

paths:
  /uploads.json:
    post:
      summary: Upload a file and receive an upload token
      parameters:
        - in: query
          name: filename
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Upload token returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"

  /issues/{issueId}.json:
    put:
      summary: Update issue with comment and uploads
      parameters:
        - in: path
          name: issueId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IssueUpdateWithUploads"
      responses:
        "200":
          description: Issue updated

  /journals/{journalId}.json:
    put:
      summary: Update a journal (comment)
      parameters:
        - in: path
          name: journalId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JournalUpdate"
      responses:
        "200":
          description: Journal updated

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Redmine-API-Key
  schemas:
    UploadResponse:
      type: object
      required: [upload]
      properties:
        upload:
          type: object
          required: [token]
          properties:
            token:
              type: string
    UploadToken:
      type: object
      required: [token, filename, content_type]
      properties:
        token:
          type: string
        filename:
          type: string
        content_type:
          type: string
    IssueUpdateWithUploads:
      type: object
      required: [issue]
      properties:
        issue:
          type: object
          required: [notes]
          properties:
            notes:
              type: string
            uploads:
              type: array
              items:
                $ref: "#/components/schemas/UploadToken"
    JournalUpdate:
      type: object
      required: [journal]
      properties:
        journal:
          type: object
          required: [notes]
          properties:
            notes:
              type: string
